# Generated by Django 3.2.3 on 2025-05-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_url',
            field=models.URLField(blank=True, default='', verbose_name='Короткая ссылка'),
            preserve_default=False,
        ),
    ]
