# Generated by Django 3.2.3 on 2025-05-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_url',
            field=models.TextField(blank=True, verbose_name='Короткая ссылка'),
        ),
    ]
